### ISSUE TITLE
[BUG]: Can't apply playbook.

### ISSUE THREAD

**Issue by Edgars-Cirulis** [meetrevision/playbook#99]
### Describe the bug

I was trying latest commits, ended up with https://github.com/meetrevision/playbook/commit/97c0ed3b6cf1aa6e1cb2a726ac5a4ed686f56af2 and it thows an error.

```Title: Error adding tasks in C:\Users\Edgars\AppData\Local\Temp\AME\Playbooks\Revision-ReviOS\Configuration\features\revision\scheduled-tasks.yml.
Message: (Line: 2, Col: 1, Idx: 4) - (Line: 2, Col: 1, Idx: 4): Exception during deserialization

StackTrace:    at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](IParser parser)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)
   at TrustedUninstaller.Shared.Parser.ConfigParser.Add(String filename)
   at TrustedUninstaller.Shared.AmeliorationUtil.AddTasks(String configPath, String file)

Date/Time: 5/3/2024 3:13:28 PM
============================================
Title: Error adding tasks in C:\Users\Edgars\AppData\Local\Temp\AME\Playbooks\Revision-ReviOS\Configuration\features\revision\scheduled-tasks.yml.
Message: (Line: 2, Col: 1, Idx: 4) - (Line: 2, Col: 1, Idx: 4): Exception during deserialization

StackTrace:    at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](IParser parser)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)
   at TrustedUninstaller.Shared.Parser.ConfigParser.Add(String filename) in ./TrustedUninstaller.Shared/Parser/ConfigParser.cs:line 89
   at TrustedUninstaller.Shared.AmeliorationUtil.AddTasks(String configPath, String file) in ./TrustedUninstaller.Shared/AmeliorationUtil.cs:line 70

Date/Time: 5/3/2024 3:13:28 PM
============================================
```

### Steps to reproduce

.

### Expected behavior

.

### Environment

.

### Have you searched for similar issues?

- [X] I have searched for similar issues and found none.

**Comment by gitchuon** [comment]
May i ask a question? Is building ReviOS from source is a good idea or I need to wait until it release a new version. I've never use ReviOS before.

**Comment by Edgars-Cirulis** [comment]
Fixed
